var MyName="Mamata";
console.log("The type of MyName=Mamata is-->", typeof(MyName));
var PIN=444603;
console.log("The type of PIN=444603 is-->",typeof(PIN));
var is_married=true;
console.log("The type of is_married=true is-->",typeof (is_married));
let list=[1,2,3,4,5];
console.log("The type of list is-->", typeof(list));
let blank_output=null;
console.log("The type of blanck_output is-->",typeof(blank_output));
let ship=undefined;
console.log("The type of ship is-->",typeof(ship));
