var p_name="Prashant";
var age=22;
var city='Pune';
var married_status=false;
console.warn("-------------------------------");
var value_type;
value_type= typeof "Prashant";
console.log(value_type);
console.log(typeof false);
console.log(typeof "Mamata");
console.log("===============");
console.log(typeof p_name);
console.log(typeof age);
console.log(typeof married_status);
console.log("===========");
console.warn("-------------------------------");
var my_project_name;
console.log(my_project_name);
console.log("================");
console.log(typeof my_project_name);
var my_properties=null;
console.log(my_properties);
var my_project_name;
console.log(my_project_name);
console.warn("-------------------------------");
var x=["Banana","Mango","Grapes"];
console.log(typeof x);
var y=["postive","self-motivated"];
console.log(typeof y);
console.warn("-------------------------------");
var a=100;var b="Angular";var c= true;
console.log(a,b,c);
console.log(typeof a,typeof b,typeof c);
console.warn("-------------------------------");
let array=["Apple","Banana"];
console.log("The type of array:",typeof array);
console.warn("-------------------------------");
let PI=null;let PIN=444101;
console.log(typeof PI,typeof PIN);