const array_numbers=[20,31,40,25,23,11,29,9,60,2,11];
let arrayLength=array_numbers.length;
console.log("Question 1");
console.log("Total Length of array:-",arrayLength);
console.log("--------------------------------------------------------");
console.log("Question 2");
let first=array_numbers[0];
console.log("First Element of array:-",first);
let last=array_numbers[arrayLength-1];
console.log("Last Element of array:-",last);
console.log("--------------------------------------------------------");
console.log("Question 3");
let Third_last=array_numbers[arrayLength-3];
console.log("Third Last Element of array:-",Third_last);
console.log("--------------------------------------------------------");
console.log("Question 4 Even Numbers from Array");
console.log("--------------------------------------------------------");
console.log("Question 5 Odd Numbers from Array");
console.log("--------------------------------------------------------");
console.log("Question 6 Even Positioned elements from Array");
console.log("--------------------------------------------------------");
console.log("Question 7 Odd Positioned elements from Array");
console.log("--------------------------------------------------------");
console.log("Question 8");
console.log("--------------------------------------------------------");
console.log("Question 9");
console.log("--------------------------------------------------------");
console.log("Question 10");
console.log("--------------------------------------------------------");
console.log("Is 115 available in given array:-",array_numbers.includes(115));
console.log("--------------------------------------------------------");
console.log("Question 11");
console.log("Is 23 available in given array:-",array_numbers.includes(23));
